#!/usr/bin/env sh

function send(){
	local id="$1"
	local caption_string="$2"
	local image_location="$3"
	local token="$TG_TOKEN"
	local url="https://api.telegram.org/bot$token/sendPhoto"
	curl -s -X POST $url \
		-F chat_id=$id \
		-F caption="$caption_string" \
		-F photo=@$image_location
}

function usage(){
	echo "Usage: $0 <chat-id> <caption> <path-to-image>"
}

function main(){
	local chat_id="$1"
	local caption="$2"
	local image="$3"

	if [[ -z $chat_id || -z $caption || -z $image ]]; then
		usage
		exit 1
	fi

	send "$chat_id" "$caption" "$image"
}

main "$@"
