#!/usr/bin/env sh

function send(){
	local id="$1"
	local caption_string="$2"
	local video_location="$3"
	local token="$TG_TOKEN"
	local url="https://api.telegram.org/bot$token/sendVideo"
	curl -s -X POST $url \
		-F chat_id=$id \
		-F caption="$caption_string" \
		-F video=@"$video_location"
}

function usage(){
	echo "Usage: $0 <chat-id> <caption> <path-to-video>"
}

function main(){
	local chat_id="$1"
	local caption="$2"
	local video="$3"

	if [[ -z $chat_id || -z $caption || -z $video ]]; then
		usage
		exit 1
	fi

	send "$chat_id" "$caption" "$video"
}

main "$@"
