#!/usr/bin/env sh

function send(){
	local CAPTION_STRING="$1"
	local IMAGE_LOCATION="$2"
	local TOKEN="$TG_TOKEN"
	local ID="$TG_CHAT_ID"
	local URL="https://api.telegram.org/bot$TOKEN/sendPhoto"
	curl -s -X POST $URL \
		-F chat_id=$ID \
		-F caption="$CAPTION_STRING" \
		-F photo=@$IMAGE_LOCATION
}

send "$1" "$2"
